---
- name: Ubuntu Jammy 22.04
  hosts: all
  vars:
    container_user: semaphore
  vars_files:
    - vars/{{ ansible_architecture }}.yml
  become: true
  become_user: root
  roles:
    - upgrade
    - system_tools
    - python
    - erlang
    - awscli
    - cloudwatch_agent
    - docker
    - users
    - agent
    - cleanup
