---
- name: Run apt update
  ansible.builtin.command: apt -y update

- name: Run apt dist-upgrade
  ansible.builtin.command: apt -fuy -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" dist-upgrade
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Run apt autoremove
  ansible.builtin.command: apt -y autoremove

- name: Reboot
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible for kernel updates"
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime
  tags:
    - reboot
