---
- name: Download awscli
  ansible.builtin.unarchive:
    src: "{{ awscli_url }}"
    dest: /tmp/
    mode: "0755"
    remote_src: true

- name: Install awscli
  ansible.builtin.command: /tmp/aws/install -i /usr/local/aws -b /usr/local/bin

- name: Cleanup awscli
  ansible.builtin.file:
    path: "/tmp/aws"
    state: absent
