---
- name: Create Python 3 symlink
  ansible.builtin.file:
    src: "/usr/bin/python3"
    path: "/usr/bin/python"
    state: link

- name: Install pip3
  ansible.builtin.apt:
    pkg:
      - python3-pip

- name: Install botocore
  ansible.builtin.pip:
    name:
      - boto3
      - botocore
