---
- name: Create Python 3 symlink
  ansible.builtin.file:
    src: "/usr/bin/python3"
    path: "/usr/bin/python"
    state: link

- name: Install pip3
  ansible.builtin.apt:
    pkg:
      - python3-pip

- name: Install botocore and boto3
  ansible.builtin.apt:
    pkg:
      - python3-boto3
      - python3-botocore
    state: present
