---
- name: Install system tools
  apt:
    pkg:
      - apt-transport-https
      - apt-utils
      - ca-certificates
      - curl
      - software-properties-common
      - zip
      - unzip
      - jq
      - make
      - gnupg
      - tree
      - wget
    state: latest
    update_cache: yes

- name: Install yq
  get_url:
    url : "{{yq_url}}"
    dest: /usr/local/bin/yq
    mode: '0755'
    force: yes