---
- name: Add Docker GPG apt Key
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: yes

- name: Install Docker
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Configure Docker service
  service:
    name: docker
    state: started
    enabled: true

- name: Install Docker Compose
  get_url:
    url : "{{ docker_compose_url }}"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
    force: yes
