---
- name: Remove apt cache
  ansible.builtin.command: apt clean

- name: Run apt autoremove
  ansible.builtin.command: apt autoremove -q -y

- name: Remove man
  ansible.builtin.command: apt remove -y --purge man-db
