---
- name: Add semaphore user
  ansible.builtin.user:
    name: semaphore
    shell: /bin/bash
    create_home: true
    state: present
    groups: docker
    append: true

- name: Allow passwordless sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^semaphore'
    line: 'semaphore ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
